FROM --platform=linux/amd64 python:3.14-slim

WORKDIR /app

COPY requirements.txt main.py /app/
RUN pip install --no-cache-dir --upgrade -r requirements.txt

RUN useradd -r -u 1001 -g 0 appuser && chown -R 1001:0 /app
USER 1001

EXPOSE 8080

CMD ["python3", "main.py"]
