apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: service-c-allow-service-b
  namespace: servicemesh-apps
spec:
  selector:
    matchLabels:
      app: service-c
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/servicemesh-apps/sa/service-b
