apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  namespace: istio-system
spec:
  namespace: istio-system
  version: v1.28-latest
  values:
    pilot:
      trustedZtunnelNamespace: ztunnel
    profile: ambient
    meshConfig:
      enableTracing: true
      defaultProviders:
        metrics:
          - prometheus
        tracing:
          - otel
      extensionProviders:
      - name: otel
        opentelemetry:
          port: 4317
          service: otel-collector.tempostack.svc.cluster.local
      discoverySelectors:
      - matchLabels:
          istio-discovery: enabled