# yaml-language-server: $schema=https://raw.githubusercontent.com/open-telemetry/opentelemetry-operator/main/config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: tempostack
spec:
  observability:
    metrics: {}
  deploymentUpdateStrategy: {}
  volumes:
    - name: cabundle
      configMap:
        name: openshift-service-ca.crt
  volumeMounts:
    - name: cabundle
      mountPath: /var/run/ca
      readOnly: true
  config:
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token
    exporters:
      otlphttp:
        endpoint: "https://tempo-tempostack-gateway.tempostack.svc.cluster.local:8080/api/traces/v1/dev"
        auth:
          authenticator: bearertokenauth
        tls:
          ca_file: /var/run/ca/service-ca.crt
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
    service:
      extensions:
        - bearertokenauth
      pipelines:
        traces:
          exporters:
            - otlphttp
          receivers:
            - otlp
          processors: []
