apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: apps-gateway
  namespace: servicemesh-apps
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: v1
kind: Service
metadata:
  name: apps-gateway
  namespace: servicemesh-apps
  labels:
    gateway.networking.k8s.io/gateway-name: apps-gateway
spec:
  ports:
    - name: status-port
      protocol: TCP
      appProtocol: tcp
      port: 15021
      targetPort: 15021
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    gateway.networking.k8s.io/gateway-name: apps-gateway
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apps-gateway
  namespace: servicemesh-apps
spec:
  to:
    kind: Service
    name: apps-gateway
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None