apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: servicemesh-apps

resources:
- ns.yml
- pod-monitors.yml
- a-deploy.yml
- b-deploy.yml
- c-v1-deploy.yml
- c-v2-deploy.yml
- route.yml