apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  labels:
    app: service-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  labels:
    app: service-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-c
  labels:
    app: service-c
