# Build
FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/openjdk-25 as builder

COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .
COPY src src

RUN ./mvnw -B package

# Run
FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/openjdk-25-runtime

COPY --from=builder /home/default/target/service-c-1.0.0-SNAPSHOT-runner.jar .

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "service-c-1.0.0-SNAPSHOT-runner.jar"]