apiVersion: kiali.io/v1alpha1
kind: Kiali
annotations:
  ansible.sdk.operatorframework.io/reconcile-period: 60s
metadata:
  name: kiali-user-workload-monitoring
  namespace: istio-system
spec:
  deployment:
    cluster_wide_access: true
    discovery_selectors:
      default:
      - matchExpressions:
        - key: istio-discovery
          operator: In
          values:
          - enabled
    logger:
      log_level: info
  external_services:
    perses:
      enabled: true
      url_format: openshift
      project: perses-dev
      is_core: false
      auth:
        type: none
      dashboards:
      - name: Istio Mesh Dashboard
        variables:
          namespace: var-namespace
          workload: var-workload
          datasource: var-datasource
      - name: Istio Service Dashboard
        variables:
          datasource: var-datasource
          namespace: var-namespace
          service: var-service
          version: var-version
      - name: Istio Workload Dashboard
        variables:
          datasource: var-datasource
          namespace: var-namespace
          version: var-version
          workload: var-workload
      - name: Istio Ztunnel Dashboard
        variables:
          namespace: var-namespace
          workload: var-workload
    prometheus:
      auth:
        ca_file: /kiali-cabundle/service-ca.crt
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
