apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service-monitor.yml
- pod-monitor.yml
- access-logging.yml
- clusterrolebinding.yml
- perses-namespace.yml
- perses-uiplugin.yml
- perses-datasource.yml
- perses-dashboards/istio-control-plane.yaml
- perses-dashboards/istio-mesh.yaml
- perses-dashboards/istio-performance.yaml
- perses-dashboards/istio-workload-dashboard.yaml
- perses-dashboards/istio-service-dashboard.yaml
- perses-dashboards/istio-ztunnel-dashboard.yaml
- kiali.yml
- ossm-console.yml
